### PR TITLE
Localization support

### PR DESCRIPTION
**Pull request by Teknoist**
I messed up old pull request

### CODE REVIEW

**Comment by ScrubN** [comment]
Thanks for the help! If the Turkish translation needs more edits in the future you can make the PRs to master

**Comment by Teknoist** [comment]
I'm happy to be able to help, but because of the translation, the ui has some errors, shifted (not aligned properly) elements and unreadable text. I will send screenshots about them.

**Comment by Teknoist** [comment]
image
image
image

**Comment by Teknoist** [comment]
image

**Comment by ScrubN** [comment]
> image

Didn't realize I forgot to add those, whoops.

As for the cutoff issues, I'll try to make them wrap.
Edit: I managed to fix the ffmpeg warning wrap and button wrap issues along with a few others you didn't mention
image
image

Unfortunately we can't make the window names automagically use a translation key, we would have to add a piece of code to the initialization functions to grab the localized names. Maybe I'll see about adding that

**Pull request merged**
