### PR TITLE
Localization support for Turkish

### PR DESCRIPTION
**Pull request by Teknoist**
I think I made it this time :P

image

### CODE REVIEW

**Comment by ScrubN** [comment]
Now that every other GUI change has been merged, localization support is nearly ready.

While working on other features I discovered that several labels in the chat render section were blatantly incorrect and had to be updated b5a109aed83b70a4ce64e06a6ca406832ac54f59.

Also I found an awesome extension for Visual Studio 2022 that should make translating so much easier https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager. If you install it, it will be very obvious which translations were added or had to be changed
image

**Comment by Teknoist** [comment]
I don't understand, are you saying that the translations of the red marked fields are wrong?

**Comment by ScrubN** [comment]
> I don't understand, are you saying that the translations of the red marked fields are wrong?

The tool colors fields based on context. If it is both red and empty then that means one of 2 things:
1. The english field is red and empty = The key was renamed/removed
2. The turkish field is red and empty = The key was added and no translation currently exists.

I don't know why these rows are red, they shouldn't be.
image

**Comment by Teknoist** [comment]
I think ı broke something help 😞

**Pull request closed without merging**
